### ISSUE TITLE
TypeError: $.ngAnnotate is not a function

### ISSUE THREAD

**Issue by manueldeutsch** [osahan/generator-sass-gulp#1]
Hi, i get this error on gulp build:

`TypeError: $.ngAnnotate is not a function`

**Comment by osahan** [comment]
@mantsch, sorry I don't see any dependency and any trace of ngAnnotate in code now. Could you please try to update your generator-sass-gulp and start a new project to test.

**Comment by peterholcomb** [comment]
@osahan Look in your build.js on line 23.  Also, you are using uglify without including it in your npm.  This doesn't seem to be a working generator at all in the sense that you can't build the project after you generate it.  Seems to be a waste of time to install this.

**Comment by osahan** [comment]
@peterholcomb here is the template for [_build.js](https://github.com/osahan/generator-sass-gulp/blob/master/generators/app/templates/_build.js)  and it kicks in `gulp.task('build', ['styles:build']);` and you are right I am not using uglify, I am using [minifyCss ](https://github.com/osahan/generator-sass-gulp/blob/master/generators/app/templates/_styles.js#L67), and it is included in my [_package.json](https://github.com/osahan/generator-sass-gulp/blob/master/generators/app/templates/_package.json) 

I tried to install and build a test project (I have node v5 installed) and I did not see any error.

Could you please try this:

Upgrade you node version, and if you are working with multiple node versions, you can use `nvm`  to switch between node versions.

Run `yo`
Select `Upgrade your generators` 
Select `generator-sass-gulp`

Generate a new project `mkdir my-sass-project && cd $_`

Run `gulp build`

**Comment by stegrams** [comment]
There are three missing devDependencies on template's package.json

   "gulp-ng-annotate": "^2.0.0",
   "gulp-uglify": "^2.0.0",
   "uglify-save-license": "^0.4.1",

After manually including those and `npm install` solved the issue for me.

**Comment by osahan** [comment]
Updated template's package.json to include missing dependencies 
https://github.com/osahan/generator-sass-gulp/commit/7f2e84f86ee8e75e6f52e92f5722b286fbdceae5
